import React, {useEffect, useLayoutEffect} from 'react';

export interface JsompWindowProps {
  /**
   * Page title (document.title)
   */
  title?: string;

  /**
   * Page icon URL (favicon)
   */
  favicon?: string;

  /**
   * Theme identifier (set to html tag's data-theme attribute)
   */
  theme?: string;

  /**
   * Language identifier (set to html tag's lang attribute)
   */
  lang?: string;

  /**
   * document.body class name
   */
  bodyClass?: string;

  /**
   * document.body inline styles
   */
  bodyStyle?: React.CSSProperties;

  /**
   * Whether to intercept window close/refresh (beforeunload)
   * Can be boolean or custom prompt text (some modern browsers may ignore custom text)
   */
  preventUnload?: boolean | string;

  /**
   * Pass through all event handlers (Action Tags generated onEvent will be mounted to window here)
   */
  [key: string]: any;
}

/**
 * JsompWindow component
 *
 * This is a "virtual node" component that doesn't render anything on screen (returns null),
 * but is responsible for transforming JSOMP node properties into global window or document state/event listeners.
 */
export const JsompWindow: React.FC<JsompWindowProps> = (props) => {
  const {
    title,
    favicon,
    theme,
    lang,
    bodyClass,
    bodyStyle,
    preventUnload,
    ...rest
  } = props;

  // 1. Sync page title
  useLayoutEffect(() => {
    if (title !== undefined) {
      const originalTitle = document.title;
      document.title = title;
      return () => {
        document.title = originalTitle;
      };
    }
  }, [title]);

  // 2. Sync Favicon
  useLayoutEffect(() => {
    if (favicon) {
      let link: HTMLLinkElement | null = document.querySelector("link[rel~='icon']");
      const originalHref = link?.href;

      if (!link) {
        link = document.createElement('link');
        link.rel = 'icon';
        document.head.appendChild(link);
      }

      link.href = favicon;

      return () => {
        if (link && originalHref !== undefined) {
          link.href = originalHref;
        }
      };
    }
  }, [favicon]);

  // 3. Sync HTML root attributes (Theme & Lang)
  useLayoutEffect(() => {
    if (theme) {
      document.documentElement.setAttribute('data-theme', theme);
    }
    if (lang) {
      document.documentElement.setAttribute('lang', lang);
    }
  }, [theme, lang]);

  // 4. Manage Body class names
  useLayoutEffect(() => {
    if (bodyClass) {
      const classes = bodyClass.split(/\s+/).filter(Boolean);
      document.body.classList.add(...classes);
      return () => {
        document.body.classList.remove(...classes);
      };
    }
  }, [bodyClass]);

  // 5. Manage Body styles
  useLayoutEffect(() => {
    if (bodyStyle) {
      const originalStyle = document.body.style.cssText;
      Object.assign(document.body.style, bodyStyle);
      return () => {
        document.body.style.cssText = originalStyle;
      };
    }
  }, [bodyStyle]);

  // 6. Global event binding (implement global Action Tags)
  useEffect(() => {
    const activeListeners: Array<{type: string; handler: any}> = [];

    Object.entries(rest).forEach(([propName, handler]) => {
      // Identify properties starting with 'on' that have function values (usually handlers generated by ActionTagsPlugin)
      if (propName.startsWith('on') && typeof handler === 'function') {
        // Convert React-style event names to native lowercase event names
        // e.g.: onKeyDown -> keydown, onClick -> click, onResize -> resize
        const nativeType = propName.slice(2).toLowerCase();

        const wrappedHandler = (e: any) => {
          handler(e);
        };

        window.addEventListener(nativeType, wrappedHandler);
        activeListeners.push({type: nativeType, handler: wrappedHandler});
      }
    });

    return () => {
      activeListeners.forEach(({type, handler}) => {
        window.removeEventListener(type, handler);
      });
    };
  }, [rest]);

  // 7. Page unload interception
  useEffect(() => {
    if (preventUnload) {
      const handleBeforeUnload = (e: BeforeUnloadEvent) => {
        e.preventDefault();
        e.returnValue = typeof preventUnload === 'string' ? preventUnload : '';
        return e.returnValue;
      };
      window.addEventListener('beforeunload', handleBeforeUnload);
      return () => window.removeEventListener('beforeunload', handleBeforeUnload);
    }
  }, [preventUnload]);

  // Render no visual content
  return null;
};
